### ISSUE TITLE
Services - Stop

### ISSUE THREAD

**Issue by PandeoF1** [PandeoF1/42-taskmaster#72]
future: <Task finished name='Task-648' coro=<Service.stop() done, defined at /workspaces/42-taskmaster/src/taskmaster/service.py:443> exception=ProcessLookupError()> - /usr/local/lib/python3.11/asyncio/base_events.py:1771
Traceback (most recent call last):
  File "/workspaces/42-taskmaster/src/taskmaster/service.py", line 451, in stop
    await process.stop(
  File "/workspaces/42-taskmaster/src/taskmaster/service.py", line 193, in stop
    self._process.send_signal(stopsignal.value)
  File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 140, in send_signal
    self._transport.send_signal(signal)
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 145, in send_signal
    self._check_proc()
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 142, in _check_proc
    raise ProcessLookupError()
ProcessLookupError

**Comment by PandeoF1** [comment]
only if not started
